# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI image and Testers 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: lfmsp/node_d_stem_final:v1.0
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: GETs 
        run: curl -X GET localhost:3000/stemdoers | grep "\"success\":true"
